//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTGS2.BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RTGSGen2DBContext : DbContext
    {
        public RTGSGen2DBContext()
            : base("name=RTGSGen2DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OutgoingSingleCredit> OutgoingSingleCredit { get; set; }
    
        public virtual ObjectResult<OutgoingSingleCredit> ProcessOutgoingSingleCredit(string tRN, string date)
        {
            var tRNParameter = tRN != null ?
                new ObjectParameter("TRN", tRN) :
                new ObjectParameter("TRN", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutgoingSingleCredit>("ProcessOutgoingSingleCredit", tRNParameter, dateParameter);
        }
    
        public virtual ObjectResult<OutgoingSingleCredit> ProcessOutgoingSingleCredit(string tRN, string date, MergeOption mergeOption)
        {
            var tRNParameter = tRN != null ?
                new ObjectParameter("TRN", tRN) :
                new ObjectParameter("TRN", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutgoingSingleCredit>("ProcessOutgoingSingleCredit", mergeOption, tRNParameter, dateParameter);
        }
    
        public virtual int GenerateOutgoingSingleCredit(string tRN)
        {
            var tRNParameter = tRN != null ?
                new ObjectParameter("TRN", tRN) :
                new ObjectParameter("TRN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateOutgoingSingleCredit", tRNParameter);
        }
    
        public virtual ObjectResult<OutgoingSingleCredit> GetAllOutgoingSingleCredit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutgoingSingleCredit>("GetAllOutgoingSingleCredit");
        }
    
        public virtual ObjectResult<OutgoingSingleCredit> GetAllOutgoingSingleCredit(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutgoingSingleCredit>("GetAllOutgoingSingleCredit", mergeOption);
        }
    }
}
