//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTGS2.BL
{
    using System;
    
    public enum TransactionStatus : sbyte
    {
        Unprocessed = 0,
        Processed = 1,
        Generated = 2
    }
}
